### ISSUE TITLE
kdevelop-9999 doesn't seem to need plasma

### ISSUE THREAD

**Issue by BigBigos** [gentoo/kde#131]
I wanted to build kdevelop5 on KDE4 desktop.

Since kdevelop-9999.ebuild requires kde-frameworks/plasma, I was unable to build it without replacing KDE4 plasma. The reason is that kde-frameworks/plasma requires kde-frameworks/kactivities, which replaces kde-base/kactivities required by KDE4 plasma

I manually removed this dependency and still managed to build kdevelop5. I think that this dependency is not really needed, especially without "runner" use flag.

**Comment by kensington** [comment]
We should check the upstream source - it may well have changed since the ebuild was written (the perils of live ebuilds).

As as workaround, you can build kde-base/kactivities with minimal USE flag to allow it to coexist with kde-frameworks/kactivities.

**Comment by kensington** [comment]
Fixed in fd14d56a18ebb16d1ea045b3d52f7a005f0b8cf6 by introducing plasma USE flag.
