### ISSUE TITLE
Make dependency on qtwebkit optional in plasma 5

### ISSUE THREAD

**Issue by ff2000** [gentoo/kde#158]
qtwebkit is a quite huge package to build. I would like to avoid installing it.
Currently there are two packages that depend hard on qtwebkit, though they only optionally require it in the CMakeLists.txt:
* libksysguard for the processui
* plasma-workspace for drkonqi
I removed those deps locally and everything built fine.

I can come up with a PR if you agree with making qtwebkit optional.

**Comment by kensington** [comment]
When the ebuild was written, qtwebkit was hard-required upstream. Now that's changed, I agree making it optional is a good idea.

**Comment by kensington** [comment]
PR was merged.
