### ISSUE TITLE
Having profiles/package.mask as a directory completely breaks Paludis

### ISSUE THREAD

**Issue by flussence** [gentoo/kde#159]
I'm kinda screwed here as an end user.

You obviously have good reason to use that feature of portage, because it's a huge list. On the other hand, I've noticed the paludis devs have a thing for "malicious compliance" and this isn't in the spec (which they wrote...), so naturally they do the most useless thing possible - which is having every single command fail if I've got the kde overlay installed.

I can work around this manually every sync with a `mv package.mask{,.d}; cat package.mask.d/* > package.mask`, but I really don't like having to do that... any ideas?

**Comment by kensington** [comment]
Unfortunately last time this issue came up, we decided against doing anything because Paludis really is a giant pain. Let's leave the issue open for a bit though so others have a chance to comment too.

The good news though is that package.* as a directory is slated for EAPI 6.

**Comment by johu** [comment]
Report this to paludis upstream and get it fixed there
https://wiki.gentoo.org/wiki/Future_EAPI/EAPI_6_tentative_features
