### ISSUE TITLE
kdevplatform-9999 fails due to incomplete tests disable

### ISSUE THREAD

**Issue by BigBigos** [gentoo/kde#190]
The kde5_src_prepare function in eclass/kde5.eclass modifies the CMakeLists.txt file in order to disable some features, like tests.

It seems to break the kdevplatform-9999 build, since it only disables tests in the root CMakeLists.txt, not in the subdirectories. Now, subdirectories also have their tests subdirectory which expect a library created by root tests subdir, which fails.

If you modify the CMakeLists.txt files, you should modify all of them.

(I looked for a more proper way to disable tests and see that you already use -DBUILD_TESTING=OFF. Which, from what I just tried, doesn't disable building tests in the least... at least for kdevplatform)

**Comment by Tommalla** [comment]
Looks like I've run into this problem while trying to merge this package.

Is anything being done to fix this? This issue is already 26 days old...

Is there any way to merge this package despite this issue?

**Comment by kensington** [comment]
I restricted the test magic to kde-{apps,frameworks,plasma} in f3331211456dcb58bc4ba8c30d67c29689dddeeb.
