### ISSUE TITLE
Missing dependencies in Plasma 5.2.95

### ISSUE THREAD

**Issue by rinaldus** [gentoo/kde#195]
I upgraded to Plasma 5.2.95 and want to report about 2 missing dependencies in 2 ebuilds:
1. kde-plasma/plasma-workspace-5.2.95 requires kde-frameworks/networkmanager-qt to be compiled. It's unable to compile without it. I have "networkmanager" USE-flag disabled but had to emerge networkmanager-qt manually, so I don't know how to be with disabled networkmanager USE-flag and this requirement.
2. kde-plasma/plasma-desktop-5.2.95 requires kde-frameworks/kpeople.
I solved these problems by installation missing dependencies and everything works ok. But you have to fix ebuilds.

Logs:
plasma-workspace: http://pastebin.com/d4gHwftY
plasma-desktop: http://pastebin.com/XXf88F4p

**Comment by kensington** [comment]
plasma-workspace unfortunately hard-requires networkmanager-qt upstream. I'm not too happy about it either, so I might look at trying to make it optional.

plasma-desktop and kpeople is a known issue and I'll try to take care of it soon.

**Comment by kensington** [comment]
I had another look and making networkmanager-qt isn't quite as simple as I originally thought unless we disable the geolocation dataengine completely (and who knows what the fallout from that might be).
