### ISSUE TITLE
kde-apps/kate-14.12.3 - missing IconThemes in CMakeLists.txt

### ISSUE THREAD

**Issue by BigBigos** [gentoo/kde#214]
The kde-apps/kate-14.12.3 CMakeLists.txt seems to be invalid - it misses the IconThemes in KF5 component list. This causes build failures.

Relevant upstream change:
https://projects.kde.org/projects/kde/applications/kate/repository/revisions/4e7c0cd61ce301907f2092cdcdeb0b7001f9589f/diff/CMakeLists.txt

**Comment by BigBigos** [comment]
kde-apps/kwrite-14.12.3 is affected too.

**Comment by BigBigos** [comment]
... and kde-apps/okteta-14.12.3 too.

**Comment by a17r** [comment]
kde-apps/kate (master) $ grep kiconthemes *
kate-14.12.3.ebuild:    $(add_frameworks_dep kiconthemes)
kate-9999.ebuild:       $(add_frameworks_dep kiconthemes)

**Comment by BigBigos** [comment]
Yes, these dependencies are in the ebuilds. They are just missing in the find_package() command in the CMakeLists.txt files. This makes the CMake mistreat "KF5::IconThemes" in target_link_libraries later on, causing build failures.

**Comment by a17r** [comment]
I guess you have kde-frameworks 5.9 installed?

https://bugs.gentoo.org/show_bug.cgi?id=546598
https://bugs.gentoo.org/show_bug.cgi?id=546594

...will be fixed by upgrade to kde-applications 15.04 (when it's there) or downgrade to kde-frameworks 5.8

**Comment by BigBigos** [comment]
Yes, I am using frameworks 5.9.

I just added quick epatch'es to these 3 ebuilds and they compiled successfully.

**Comment by mrueg** [comment]
15.04.0 is now available in the overlay. Please give this a try.
