### ISSUE TITLE
Missing app-doc/doxygen dependency on net-libs/accounts-qt

### ISSUE THREAD

**Issue by papjul** [gentoo/kde#219]
Can't compile without doxygen:
/bin/sh: doxygen: command not found
Makefile:403: recipe for target 'docs' failed
make: *** [docs] Error 127

After emerging doxygen, it compiles fine.

**Comment by kensington** [comment]
Thanks, fixed in d76f8841e03a434e5c85aba1f9ce6c4a8979e6ba.
