### ISSUE TITLE
kde-apps/lib{kdegames,kmahjongg}:5 block :4

### ISSUE THREAD

**Issue by BigBigos** [gentoo/kde#222]
There seems to be the following code in kde5.eclass (when KDE_AUTODEPS is enabled):

```
if [[ ${CATEGORY} == kde-apps ]]; then
    RDEPEND+="
        !kde-apps/${PN}:4
        !kde-base/${PN}
    "
fi
```

It seems to be right in general, since kde-apps category contains mostly individual applications.

However, the libkdegames and libkmahjongg libraries in kde-apps category are coinstallable (i.e. both :4 and :5 slots can be installed at the same time).

In kde-apps 15.04 some apps using these libs have been ported to kf5 (like kde-apps/kmines) but not all (like kde-apps/konquest). Because of that, I need both slot 4 and slot 5 versions of these libraries.

Excluding these 2 libs from the check above fixed the problem for me. The ebuilds coinstalled successfully.

**Comment by kensington** [comment]
Fixed by @a17r in 53ce4213414414d2796ad806ae47fd5ecfbc0766, b6b0ee6350195fc4f8390fc0ed0f7a9a5c8cadc0, and 27e6457fcd134733d444a81751970b54c26dbeb7.
