### ISSUE TITLE
kde-plasma/kscreen-5.3.0 KCM doesn't render correctly without dev-qt/qtgraphicaleffects

### ISSUE THREAD

**Issue by BigBigos** [gentoo/kde#225]
The kde-plasma/kscreen-5.3.0 compiles correctly without this package. However, the KCM (system settings configuration module for kscreen) misrenders, due to missing qml file.

After emerging dev-qt/qtgraphicaleffects, the KCM works (re-emerging kde-plasma/kscreen wasn't needed).

**Comment by kensington** [comment]
Thanks, fixed in a141c15e5f49f4b70458727bcd5cb8117e7f0185.
