### ISSUE TITLE
Documentation/package.accept_keywords/kde-4.14.keywords has incorrect entries after kde-base packages move to kde-apps

### ISSUE THREAD

**Issue by Coacher** [gentoo/kde#257]
Hello.

`Documentation/package.accept_keywords/kde-4.14.keywords` file has `kde-base/kdebase-meta` and `kde-base/kde-l10n` entries.

The former is now `kde-apps/kdebase-meta` and was updated accordingly in sets, but the old `kde-base` category is still there after several regeneration iterations.

The latter is now `kde-apps/kde4-l10n` and was updated accordingly in sets, but the old `kde-base/kde-l10n` package is still there after several regeneration iterations.

It looks like there are some issues with the regeneration process.

Please fix.

**Comment by kensington** [comment]
Since the kde-apps move, the regeneration script is partially broken since kde-base category is hardcoded in several places. Fixing is definitely on the todo, but just hasn't happened yet since the script is full of spaghetti code. :)

**Comment by reavertm** [comment]
I believe this is not an issue anymore?

**Comment by Coacher** [comment]
kdebase-meta got fixed. kde-l10n is still [there](https://github.com/gentoo/kde/blob/master/Documentation/package.accept_keywords/kde-4.14.keywords#L5) and no kde-apps/kde4-l10n around.

So halfway through.

**Comment by Coacher** [comment]
More leftovers garbage: https://github.com/gentoo/kde/blob/master/Documentation/package.accept_keywords/kde-4.14.keywords#L209

oxygen-icons should be under kde-frameworks/ now: https://github.com/gentoo/kde/blob/master/Documentation/package.accept_keywords/kde-4.14.keywords#L217

**Comment by a17r** [comment]
looks like that file isn't regenerated anymore...

**Comment by Coacher** [comment]
After the last regeneration all of the above issues seem to be fixed. Thank you.
