### ISSUE TITLE
kde-plasma/plasma-meta and gtk

### ISSUE THREAD

**Issue by yellowhat** [gentoo/kde#263]
Hi.
I am usign plasma 5.3 installed with emerge -a @kde-plasma-5.3.
As you can see the only package that requires gtk+ is kde-gtk-config:

 equery depends gtk+
 * These packages depend on gtk+:
app-crypt/pinentry-0.9.4-r1 (gtk ? x11-libs/gtk+:2)
app-office/libreoffice-4.4.3.2 (gtk ? >=x11-libs/gtk+-2.24:2)
                               (gtk3 ? >=x11-libs/gtk+-3.2:3)
                               (telepathy ? >=x11-libs/gtk+-2.24:2)
app-text/ghostscript-gpl-9.15-r1 (gtk ? x11-libs/gtk+:3)
                                 (gtk ? x11-libs/gtk+:2)
dev-qt/qtgui-4.8.7 (gtkstyle ? >=x11-libs/gtk+-2.24.23-r1:2[aqua=,abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])
dev-qt/qtgui-5.4.1-r2 (gtkstyle ? x11-libs/gtk+:2)
gnome-base/librsvg-2.40.9 (tools ? >=x11-libs/gtk+-3.2.0:3)
kde-plasma/kde-gtk-config-5.3.1 (x11-libs/gtk+:2)
                                (x11-libs/gtk+:3)
media-gfx/fontforge-20150430 (gtk ? x11-libs/gtk+:2)
media-libs/libcanberra-0.30-r5 (gtk ? >=x11-libs/gtk+-2.20.0:2[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])
                               (gtk3 ? x11-libs/gtk+:3[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])
media-sound/pulseaudio-6.0 (gtk ? x11-libs/gtk+:3)
media-video/vlc-2.2.1 (libnotify ? x11-libs/gtk+:2)
net-dialup/ppp-2.4.7-r1 (gtk ? x11-libs/gtk+:2)
net-misc/networkmanager-openvpn-1.0.2 (gtk ? >=x11-libs/gtk+-3.4:3)
sys-devel/gcc-5.1.0 (awt ? =x11-libs/gtk+-2*)
x11-libs/libnotify-0.7.6-r1 (test ? x11-libs/gtk+:3[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])

 equery hasuse gtk
 * Searching for USE flag gtk ... 
[IP-] [  ] app-crypt/pinentry-0.9.4-r1:0
[IP-] [  ] app-office/libreoffice-4.4.3.2:0
[IP-] [  ] app-text/ghostscript-gpl-9.15-r1:0
[IP-] [  ] dev-vcs/git-2.4.2:0
[IP-] [  ] kde-plasma/systemsettings-5.3.1:5
[IP-] [  ] media-gfx/fontforge-20150430:0
[IP-] [  ] media-libs/libcanberra-0.30-r5:0
[IP-] [  ] media-sound/pulseaudio-6.0:0
[IP-] [  ] net-dialup/ppp-2.4.7-r1:0/2.4.7
[IP-] [  ] net-misc/networkmanager-openvpn-1.0.2:0
[IP-] [  ] sys-auth/polkit-0.112-r3:0

 equery hasuse gtk3
 * Searching for USE flag gtk3 ... 
[IP-] [  ] app-office/libreoffice-4.4.3.2:0
[IP-] [  ] media-libs/libcanberra-0.30-r5:0

 equery hasuse gtkstyle
 * Searching for USE flag gtkstyle ... 
[IP-] [  ] dev-qt/qtgui-4.8.7:4
[IP-] [  ] dev-qt/qtgui-5.4.1-r2:5
[IP-] [  ] dev-qt/qtwidgets-5.4.1:5

Is it possible to make kde-gtk-config optional as dependence of kde-plasma/plasma-meta?

Thanks

**Comment by wojtask9** [comment]
On my system situation is the same. None of my packages uses gtk+3.
Additionally the same could be done with ksysguard because it pulls whole qtwebkit with all ruby dependencies

**Comment by johu** [comment]
Thanks. Added gtk use flag in c8c9181bef67b8f227fca76c407a576775ca9447, changes also applied to the version in tree.

**Comment by yellowhat** [comment]
Even with:
[ebuild   R   #] kde-plasma/systemsettings-5.3.1:5::gentoo  USE="-debug -gtk -handbook" 0 KiB
[ebuild   R   #] kde-plasma/plasma-meta-5.3.1-r1:5::kde  USE="bluetooth display-manager sddm -gtk -networkmanager -wallpapers" 0 KiB

kde-plasma/kde-gtk-config is still required.

**Comment by kensington** [comment]
Can you please add portage output where kde-gtk-config is getting pulled in, with --tree option?

**Comment by yellowhat** [comment]
Did you mean this:

equery depends kde-gtk-config
 * These packages depend on kde-gtk-config:
kde-plasma/plasma-meta-5.3.1-r1 (gtk ? >=kde-plasma/kde-gtk-config-5.3.1:5)
kde-plasma/systemsettings-5.3.1 (gtk ? >=kde-plasma/kde-gtk-config-5.3.1:5)

**Comment by kensington** [comment]
According to that, kde-gtk-config is conditional on gtk USE flag.

**Comment by yellowhat** [comment]
OK. But as you can see:

[ebuild R #] kde-plasma/systemsettings-5.3.1:5::gentoo USE="-debug -gtk -handbook" 0 KiB
[ebuild R #] kde-plasma/plasma-meta-5.3.1-r1:5::kde USE="bluetooth display-manager sddm -gtk -networkmanager -wallpapers" 0 KiB

that use flag is disabled.
