### ISSUE TITLE
Dolphin embedded terminal

### ISSUE THREAD

**Issue by yellowhat** [gentoo/kde#273]
Hi all.
I have installed dolphin and konsole 15.04.2 but if I press F4 in dolphin it creates a bottom panel but it is blank, does not contain a terminal window.
If I press Shift+F4 it opens a new konsole window as it should.
Is something missing?

Thanks

**Comment by a17r** [comment]
dolphin-15.04.2:4 + konsole-15.04.2:5 makes us sad. 15.08 will fix that, until then I recommend unmasking dolphin-9999:5.

**Comment by johu** [comment]
Upstream issue.
