### ISSUE TITLE
kde-apps/kdenlive (assembly error)

### ISSUE THREAD

**Issue by nikolasha21** [gentoo/kde#276]
Hello!

kde-apps/kdenlive-9999

I ask to pay attention, at assembly of this package there is a mistake in the 116th line

/usr/include/mlt++/MltFrame.h:40:4: note:   candidate expects 1 argument, 0 provided
src/CMakeFiles/kdenlive.dir/build.make:3030: recipe for target 'src/CMakeFiles/kdenlive.dir/monitor/glwidget.cpp.o' failed
make[2]: *** [src/CMakeFiles/kdenlive.dir/monitor/glwidget.cpp.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/kde-apps/kdenlive-9999/work/kdenlive-9999_build'
CMakeFiles/Makefile2:414: recipe for target 'src/CMakeFiles/kdenlive.dir/all' failed
make[1]: *** [src/CMakeFiles/kdenlive.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/kde-apps/kdenlive-9999/work/kdenlive-9999_build'
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: kde-apps/kdenlive-9999::kde failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=kde-apps/kdenlive-9999::kde'`,
 * the complete build log and the output of `emerge -pqv '=kde-apps/kdenlive-9999::kde'`.
 * The complete build log is located at '/var/tmp/portage/kde-apps/kdenlive-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/kde-apps/kdenlive-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/kde-apps/kdenlive-9999/work/kdenlive-9999_build'
 * S: '/var/tmp/portage/kde-apps/kdenlive-9999/work/kdenlive-9999'

**Comment by kensington** [comment]
We are tracking this at https://bugs.gentoo.org/show_bug.cgi?id=550698 (short story is we need newer version of mlt in the tree).
