### ISSUE TITLE
plasma5 should depends on udisks2 somehow

### ISSUE THREAD

**Issue by wojtask9** [gentoo/kde#284]
Yesterday I was able to remove kdelibs4 from my system.
After emerge --depclean portage removed udisks2 because none of kf5 or plasma5 packages have dependency to udisk2.
Without this "runtime" dependency Device Notifier in plasma5 won't work.

**Comment by kensington** [comment]
Thanks, fixed in eb8026beb703b19716c9c79e9d896392ce441dd5. It'll be in the main tree in a week or so with frameworks 5.12.
