### ISSUE TITLE
kde-apps/kmix-15.04.3: kmix-15.04.2-alsa-optional.patch

### ISSUE THREAD

**Issue by yellowhat** [gentoo/kde#294]
Hi all,
I am trying to emerge kde-apps/kmix-15.04.3 but I get this error:

>>> Emerging (1 of 1) kde-apps/kmix-15.04.3::kde
 * kmix-15.04.3.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                   [ ok ]
>>> Unpacking source...
>>> Unpacking kmix-15.04.3.tar.xz to /var/tmp/portage/kde-apps/kmix-15.04.3/work
>>> Source unpacked in /var/tmp/portage/kde-apps/kmix-15.04.3/work
>>> Preparing source in /var/tmp/portage/kde-apps/kmix-15.04.3/work/kmix-15.04.3 ...

 * Cannot find $EPATCH_SOURCE!  Value for $EPATCH_SOURCE is:
 * 
 *   /var/lib/layman/kde/kde-apps/kmix/files/kmix-15.04.2-alsa-optional.patch
 *   ( kmix-15.04.2-alsa-optional.patch )

 * ERROR: kde-apps/kmix-15.04.3::kde failed (prepare phase):
 *   Cannot find $EPATCH_SOURCE!
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 3560:  Called kde5_src_prepare
 *   environment, line 2660:  Called cmake-utils_src_prepare
 *   environment, line  970:  Called _execute_optionally 'src_prepare'
 *   environment, line  462:  Called enable_cmake-utils_src_prepare
 *   environment, line 1305:  Called epatch '/var/lib/layman/kde/kde-apps/kmix/files/kmix-15.04.2-alsa-optional.patch'
 *   environment, line 1389:  Called die
 * The specific snippet of code:
 *                   die "Cannot find \$EPATCH_SOURCE!";
 * 
 * If you need support, post the output of `emerge --info '=kde-apps/kmix-15.04.3::kde'`,
 * the complete build log and the output of `emerge -pqv '=kde-apps/kmix-15.04.3::kde'`.
 * The complete build log is located at '/var/tmp/portage/kde-apps/kmix-15.04.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/kde-apps/kmix-15.04.3/temp/environment'.
 * Working directory: '/var/tmp/portage/kde-apps/kmix-15.04.3/work/kmix-15.04.3'
 * S: '/var/tmp/portage/kde-apps/kmix-15.04.3/work/kmix-15.04.3'

>>> Failed to emerge kde-apps/kmix-15.04.3, Log file:

>>>  '/var/tmp/portage/kde-apps/kmix-15.04.3/temp/build.log'

 * Messages for package kde-apps/kmix-15.04.3:

 * Cannot find $EPATCH_SOURCE!  Value for $EPATCH_SOURCE is:
 * 
 *   /var/lib/layman/kde/kde-apps/kmix/files/kmix-15.04.2-alsa-optional.patch
 *   ( kmix-15.04.2-alsa-optional.patch )
 * ERROR: kde-apps/kmix-15.04.3::kde failed (prepare phase):
 *   Cannot find $EPATCH_SOURCE!
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 3560:  Called kde5_src_prepare
 *   environment, line 2660:  Called cmake-utils_src_prepare
 *   environment, line  970:  Called _execute_optionally 'src_prepare'
 *   environment, line  462:  Called enable_cmake-utils_src_prepare
 *   environment, line 1305:  Called epatch '/var/lib/layman/kde/kde-apps/kmix/files/kmix-15.04.2-alsa-optional.patch'
 *   environment, line 1389:  Called die
 * The specific snippet of code:
 *                   die "Cannot find \$EPATCH_SOURCE!";
 * 
 * If you need support, post the output of `emerge --info '=kde-apps/kmix-15.04.3::kde'`,
 * the complete build log and the output of `emerge -pqv '=kde-apps/kmix-15.04.3::kde'`.
 * The complete build log is located at '/var/tmp/portage/kde-apps/kmix-15.04.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/kde-apps/kmix-15.04.3/temp/environment'.
 * Working directory: '/var/tmp/portage/kde-apps/kmix-15.04.3/work/kmix-15.04.3'
 * S: '/var/tmp/portage/kde-apps/kmix-15.04.3/work/kmix-15.04.3'

**Comment by kensington** [comment]
Thanks, fixed in 0c10998a97dd25fe6111b851139a6ffbae3e5253.
