### ISSUE TITLE
Pkg move app-office/akonadi-server -> kde-apps/akonadi breaks update on KDE4 systems

### ISSUE THREAD

**Issue by Coacher** [gentoo/kde#327]
Hello.

I am a KDE4 user and I have app-office/akonadi-server installed because of KDEPIM. Since the said pkg move was introduced, emerge tries to pull kde-apps/akonadi and update fails because KDE5/Qt5 packages are masked on my system. Is it normal that KDE4 packages now pull kde-apps/akonadi, which in turn depends on Qt5? I believe is is not, but please correct me if I am wrong. Please fix.

This pkg move was introduced in ef104b748173fae0cbe7af3831230e1b8d82d819.

**Comment by a17r** [comment]
You need to re-install kdepimlibs and any other KDE4-package that claims to pull in kde-apps/akonadi. Packages don't actually pull that in, so there's nothing to fix. Issue arises because you installed kdepimlibs from overlay which has since been moved to tree.

**Comment by Coacher** [comment]
I see. Thank you for the explanation @a17r . Closing.
