### ISSUE TITLE
kde-apps/dolphin-15.07.90:5::kde update

### ISSUE THREAD

**Issue by yellowhat** [gentoo/kde#342]
Hi all,
I am trying to update to kde-apps/dolphin-15.07.90:5::kde but I get this blocking:

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    #] kde-apps/kio-extras-15.07.90:5::kde  USE="exif phonon sftp -debug -handbook -mtp -samba -slp {-test}" 262 KiB
[ebuild  NS   #] kde-apps/dolphin-15.07.90:5::kde [15.04.3:4/15.04::kde] USE="-debug -handbook -semantic-desktop {-test} (-thumbnail)" 642 KiB
[blocks B      ] kde-plasma/kio-extras ("kde-plasma/kio-extras" is blocking kde-apps/kio-extras-15.07.90)
[blocks B      ] kde-apps/dolphin:4 ("kde-apps/dolphin:4" is blocking kde-apps/dolphin-15.07.90)

Total: 2 packages (1 new, 1 in new slot), Size of downloads: 903 KiB
Conflict: 2 blocks (2 unsatisfied)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (kde-apps/dolphin-15.07.90:5/5::kde, ebuild scheduled for merge) pulled in by
    dolphin:5

  (kde-plasma/kio-extras-5.3.2:5/5::gentoo, installed) pulled in by
    kde-plasma/kio-extras:5 required by @kde-plasma
    >=kde-plasma/kio-extras-5.3.2:5 required by (kde-plasma/plasma-desktop-5.3.2:5/5::gentoo, installed)

  (kde-apps/dolphin-15.04.3:4/15.04::kde, installed) pulled in by
    kde-apps/dolphin:4 required by @selected

For more information about Blocked Packages, please refer to the following
section of the Gentoo Linux x86 Handbook (architecture is irrelevant):

https://wiki.gentoo.org/wiki/Handbook:X86/Working/Portage#Blocked_packages

Thanks

**Comment by a17r** [comment]
That's an unfortunate situation right now, to be solved by the plasma-5.4 update coming soon.

**Comment by yellowhat** [comment]
Is there a workaround just until august 25?

Thanks

**Comment by johu** [comment]
@yellowhat plasma-5.4 beta will be available soon

**Comment by johu** [comment]
Is releases and in kde overlay available.
