### ISSUE TITLE
Please make gstreamer optional in kde-plasma/kwin 

### ISSUE THREAD

**Issue by octoploid** [gentoo/kde#346]
kde-plasma/kwin/kwin-5.3.95.ebuild contains:
COMMON_DEPEND="
...
dev-qt/qtmultimedia:5[gstreamer,qml]

This is unnecessary. Please make the gstreamer dependency optional.

Thanks.

**Comment by kensington** [comment]
It's required to show example videos in the desktop effects kcm.

**Comment by octoploid** [comment]
Well, I don't need to see the example videos in the desktop effects kcm ;-).
I don't have gstreamer installed at all, and would like to keep my system minimal.

**Comment by kensington** [comment]
Unfortunately we don't really have any mechanism to make it optional for those who don't want a specific dependency while keeping things working out-of-the-box for everyone else.

**Comment by octoploid** [comment]
Why not make it the default for everybody, except those that specified USE="-gstreamer".

**Comment by kensington** [comment]
Unfortunately Gentoo policy generally prevents use of USE flags that only control runtime deps.

**Comment by johu** [comment]
@kensington how about to move rhe discussion about the policy  to -dev ml?

**Comment by kensington** [comment]
Until we either get an upstream option to disable the feature entirely or Gentoo mechanism to to mark recommended-but-not-required dependencies, I'm afraid there's not much we can do.

You could look at using something like package.provided if you want to help keep your system extra-minimal.
