### ISSUE TITLE
fail download konsole-15.08.0.tar.xz from kde.org

### ISSUE THREAD

**Issue by nyim** [gentoo/kde#350]
the source of this version could not be found
at http://download.kde.org/unstable/applications/
nor at http://download.kde.org/stable/applications/

>>> Downloading 'http://download.kde.org/stable/applications/15.08.0/src/konsole-15.08.0.tar.xz'
--2015-08-18 10:28:41--  http://download.kde.org/stable/applications/15.08.0/src/konsole-15.08.0.tar.xz
Resolving download.kde.org... 195.135.221.71, 2001:67c:2178:7::71
Connecting to download.kde.org|195.135.221.71|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-18 10:28:41 ERROR 403: Forbidden.

**Comment by johu** [comment]
Not released. Please read package mask reason before unmasking stuff.
