### ISSUE TITLE
"No cmake_minimum_required command is present" kioclient-15.08.0

### ISSUE THREAD

**Issue by octoploid** [gentoo/kde#353]
See https://forums.gentoo.org/viewtopic-t-1027082.html

CMake Warning (dev) in CMakeLists.txt: 
  No cmake_minimum_required command is present.  A line of code such as 

    cmake_minimum_required(VERSION 3.3) 

  should be added at the top of the file.  The version specified may be lower 
  if you wish to support older CMake versions for this project.  For more 
  information run "cmake --help-policy CMP0000". 
This warning is for project developers.  Use -Wno-dev to suppress it. 

-- Configuring incomplete, errors occurred!

**Comment by octoploid** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=558236

**Comment by kensington** [comment]
Thanks, this is a nasty bug affecting a number of packages. We will track it on the Gentoo bug you referenced.
