### ISSUE TITLE
kdepim-runtime-9999 dependecies

### ISSUE THREAD

**Issue by barolgin** [gentoo/kde#355]
Hello.
I have tried to emerge ```kde-apps/kdepim-meta``` from kde overlay and got a small trouble. Package kde-apps/kdepim-runtime-9999::kde failed to build:
```
    CMake Error at CMakeLists.txt:123 (find_package):
    Could not find a package configuration file provided by "KF5AlarmCalendar"
    (requested version 4.78.0) with any of the following names:
        KF5AlarmCalendarConfig.cmake
        kf5alarmcalendar-config.cmake
```
After resuming build with ```--keep-going=y``` option these packages were installed:
```
    kde-apps/akonadi-search-9999::kde
    kde-apps/ktnef-9999::kde
    kde-apps/kalarmcal-9999::kde
    kde-apps/akonadi-calendar-9999::kde
```
After that everything installed fine.
I do not use parallel emerge (```EMERGE_DEFAULT_OPTS="-jX"``` is not set), so the problem seems to be in ebuild dependencies. Could you fix it please, so others wouldn`t face with this problem? I think this would be easily.

**Comment by johu** [comment]
Should be fixed in 9827d8aab1822f5a226fb88451cc712b1fd8e3f6
