### ISSUE TITLE
kde-plasma/plasma-workspace USE wayland networkmanager

### ISSUE THREAD

**Issue by Revent** [gentoo/kde#398]
Option is needed to remove wayland & networkmanager  from the system.

**Comment by a17r** [comment]
Not possible afaik, plasma-workspace is using kwayland even on X11 already.

**Comment by kensington** [comment]
networkmanager dependency can be avoided by disabling the geolocation USE flag (fixed in f60ca031873826be22fe680bf8ed3d593ba23223).

As @a17r mentioned, avoiding wayland dependency is not possible because kwayland is used heavily, even on X11.
