### ISSUE TITLE
Compile of plasma-workspace-9999 failed

### ISSUE THREAD

**Issue by MikeeFlyy** [gentoo/kde#460]
Compile failed, here is relevant part f log I think

CMake Error at CMakeLists.txt:31 (find_package):
  By not providing "FindKScreenLocker.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KScreenLocker", but CMake did not find one.

  Could not find a package configuration file provided by "KScreenLocker"
  with any of the following names:

    KScreenLockerConfig.cmake
    kscreenlocker-config.cmake

  Add the installation prefix of "KScreenLocker" to CMAKE_PREFIX_PATH or set
  "KScreenLocker_DIR" to a directory containing one of the above files.  If
  "KScreenLocker" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by a17r** [comment]
yes, needs a new package not yet in overlay

**Comment by MikeeFlyy** [comment]
Thank you, manual download and compilation of KScreenLocker from KDE Git seems to solve the issue. I have plasma live as main DE on my private NB and after last update I cannot login. (OK, starting X and then kwin and plasmashell worked). Thank you for your job, it is the first bigger issue with live plasma builds for me, so this is a good score. :)

**Comment by a17r** [comment]
I guess this is also solved now.
