### ISSUE TITLE
sys-block/partition-manager-2.0.0 and sys-block/kpmcore-2.0.0 versions bump

### ISSUE THREAD

**Issue by papjul** [gentoo/kde#569]
See https://stikonas.eu/wordpress/2016/01/15/kde-partition-manager-2-0-0/
Thanks!

**Comment by kensington** [comment]
This is fixed in gentoo/gentoo@d1c4acabcdb036d539ec1021fb25eff9d842501a and gentoo/gentoo@cdfe343ee2d1b277538c66308d9d78897dd34e75
