### ISSUE TITLE
=kde-apps/kdepimlibs-15.08.3 build error

### ISSUE THREAD

**Issue by kittkott** [gentoo/kde#572]
/var/tmp/portage/kde-apps/kdepimlibs-15.08.3/work/kdepimlibs-15.08.3/akonadi/src/core/servermanager.cpp:309:32: error: ‘AKONADI_DBUS_SERVER_SERVICE’ was not declared in this scope
         return makeServi
ceName(AKONADI_DBUS_SERVER_SERVICE);
                                ^
/var/tmp/portage/kde-apps/kdepimlibs-15.08.3/work/kdepimlibs-15.08.3/akonadi/src/core/servermanager.cpp:311:32: error: ‘AKONADI_DBUS_CONTROL_SERVICE’ was not declared in this scope
         return makeServiceName(AKONADI_DBUS_CONTROL_SERVICE);
                                ^
/var/tmp/portage/kde-apps/kdepimlibs-15.08.3/work/kdepimlibs-15.08.3/akonadi/src/core/servermanager.cpp:313:32: error: ‘AKONADI_DBUS_CONTROL_SERVICE_LOCK’ was not declared in this scope
         return makeServiceName(AKONADI_DBUS_CONTROL_SERVICE_LOCK);
                                ^
/var/tmp/portage/kde-apps/kdepimlibs-15.08.3/work/kdepimlibs-15.08.3/akonadi/src/core/servermanager.cpp: In static member function ‘static QString 

Akonadi::ServerManager::agentServiceName(Akonadi::ServerManager::ServiceAgentType, const QString&)’:
/var/tmp/portage/kde-apps/kdepimlibs-15.08.3/work/kdepimlibs-15.08.3/akonadi/src/core/servermanager.cpp:325:32: error: ‘AKONADI_DBUS_SERVER_SERVICE’ was not declared in this scope
         return makeServiceName(AKONADI_DBUS_SERVER_SERVICE, QString::fromLatin1(".Agent.%1").arg(identifier));
   
emerge --info =kde-apps/kdepimlibs-15.08.3::kde 
Portage 2.2.27 (python 3.4.3-final-0, default/linux/amd64/13.0/desktop/plasma, gcc-4.9.3, glibc-2.22-r1, 4.4.0-gentoo-r1 x86_64)

System Settings

System uname: Linux-4.4.0-gentoo-r1-x86_64-Intel-R-_Core-TM-_i7-4710MQ_CPU_@_2.50GHz-with-gentoo-2.2
KiB Mem:     7835112 total,   5763108 free
KiB Swap:    4194288 total,   4194288 free
Timestamp of repository gentoo: Fri, 22 Jan 2016 01:00:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
ccache version 3.2.4 [disabled]
app-shells/bash:          4.3_p42-r1::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.22.1::gentoo
dev-lang/python:          2.7.11-r2::gentoo, 3.4.3-r7::gentoo
dev-util/ccache:          3.2.4::gentoo
dev-util/cmake:           3.4.2::gentoo
dev-util/pkgconfig:       0.29::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.20.3::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r1::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.12.6::gentoo, 1.13.4::gentoo, 1.14.1::gentoo, 1.15-r1::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.8::gentoo
sys-devel/libtool:        2.4.6-r1::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.4::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r1::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

kde
    location: /var/lib/layman/kde
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA PUEL dlj-1.1 Oracle-BCLA-JavaSE AdobeFlash-11.x skype-4.0.0.7-copyright Vivaldi"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -fomit-frame-pointer -march=core-avx2 -mfpmath=sse -fno-align-labels -ftree-loop-if-convert"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe -fomit-frame-pointer -march=core-avx2 -mfpmath=sse -fno-align-labels -ftree-loop-if-convert"
DISTDIR="/usr/portage/distfiles"
EMERGE_DEFAULT_OPTS="--autounmask=n --load-average 8 --jobs 7"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs buildsyspkg collision-protect config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync metadata-transfer news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirror.yandex.ru/gentoo-distfiles/"
LANG="ru_RU.UTF-8"
LDFLAGS="-Wl,--as-needed"
MAKEOPTS="-j9 -s"
PKGDIR="/usr/portage/packages"
PORTAGE_BUNZIP2_COMMAND="lbunzip2 -n7"
PORTAGE_BZIP2_COMMAND="lbzip2 -n7"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X \ a52 aac aacplus acl acpi alsa amd64 bash-completion berkdb bluetooth branding bzip2 cairo cdr cjk cleartype cli consolekit cpudetection cracklib crypt cups curl custom-optimization cxx dbus declarative djvu dri dri2 drm dts dvd dvdr egl emboss encode eselect exif fam ffmpeg firefox flac fontconfig fontforge fortran gdbm gif glamor gles gles1 gles2 glib gpm gsm gtk iconv introspection ipv6 jpeg jpeg2k kde kipi lcms ldap libnotify lm_sensors lzma mad mmx mmxext mng modules mp3 mp4 mpeg multilib ncurses nls nptl ogg opengl openmp pam pango pcre pda pdf phonon plasma png policykit ppds pulseaudio pypy qml qt3support qt5 raw readline sdl seccomp semantic-desktop session sna spell sse sse2 ssl startup-notification svg system-sqlite tcpd theora tiff truetype udev udisks unicode upower usb v4l v4l2 vaapi vorbis widgets wifi wmf wxwidgets x264 xattr xcb xcomposite xinerama xml xorg xscreensaver xv xvid xvmc zlib" ABI_X86="64" ALSA_CARDS="hda-intel" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="pc" INPUT_DEVICES="evdev keyboard mouse void" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer pdfimport" LINGUAS="ru en ru_RU en_US" LIRC_DEVICES="audio audio_alsa serial" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7 python3_4 pypy" PYTHON_TARGETS="python2_7 python3_4 pypy" RUBY_TARGETS="ruby23" SANE_BACKENDS="epson epson2 hp hp3500 hp3900 hp4200 hp5400 hp5590 hpljm1005 hpsj5s mustek mustek_pp mustek_usb net xerox_mfp" USERLAND="GNU" VIDEO_CARDS="intel i965 nouveau" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
USE_PYTHON="2.7 3.3"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
[build.log.zip](https://github.com/gentoo/kde/files/102658/build.log.zip)

**Comment by a17r** [comment]
Please re-sync and upgrade to 15.12.1, 15.08.3 and kdepimlibs in particular is no more ;)
