### ISSUE TITLE
kde telepathy does not work

### ISSUE THREAD

**Issue by brigadier** [gentoo/kde#587]
I can't configure kde telepathy any more. Gitting the "It appears your system is not configured properly, please ensure you have AG_PROVIDERS and/or AG_SERVICES environment variables set correctly, then restart this configuration module. Please contact your distribution if you're unsure how to proceed." error in System settings->online accounts.

It happens because of this commit: https://quickgit.kde.org/?p=kaccounts-integration.git&a=commit&h=0ba1dde28cfacff71b264bba1b43a3f6e5992406

**Comment by a17r** [comment]
They still haven't figured out a way to do this upstream?

**Comment by brigadier** [comment]
No, they haven't figured anything in upstream.
About 15.12.x - I tried to revert to 15.12.49, by masking 9999, but got message that I should unmask some packages, including kaccounts-integration. I suspect it's because some of packages, such as ktp-call-ui, just don't have 15.12 ebuild, but only the 9999 one.
I also tried to revert the changes before posting the issue (reset to e0fcaeb commit and patch), but after that I just want's able to add any account to the ktp.

**Comment by a17r** [comment]
Well, having installed ktp-call-ui, the downgrade wouldn't work. Do you actually use it? If not, just unmerge it.

**Comment by brigadier** [comment]
I was able to downgrade successfully, but connection to ICQ does not work. Authorization failed.
It worked before with the telepathy for kde4 from the net-im/ packages.

**Comment by kensington** [comment]
It was definitely discussed shipping env files with plasma-workspace upstream but I didn't see it happen yet.

**Comment by a17r** [comment]
I was able to get a connection to ICQ with 15.12.2, save for the fact that they claim my account to be blocked (and they won't get my phone number just for testing).

``telepathy-haze`` needs to be installed (pulled in by ``net-im/telepathy-connection-managers[icq]``

**Comment by brigadier** [comment]
thank you a17r, net-im/telepathy-connection-managers[icq] fixed it for me

**Comment by a17r** [comment]
Update in the relevant upstream bug, seems it is fixed: https://bugs.kde.org/show_bug.cgi?id=347219

**Comment by a17r** [comment]
...successfully tested with my jabber account right now.

**Comment by johu** [comment]
Testted it with jabber + icq. Closing then.
