### ISSUE TITLE
=kde-apps/kdepim-15.12.2::kde should deps on =kde-apps/libktnef-15.12.2

### ISSUE THREAD

**Issue by init6** [gentoo/kde#602]
[although…](https://github.com/gentoo/kde/blob/master/kde-apps/kdepim/kdepim-15.12.2.ebuild#L164)

    # emerge -1 =kde-apps/kdepim-15.12.2

    These are the packages that would be merged, in order:

    [ebuild   R   #] kde-apps/kdepim-15.12.2:5::kde  USE="handbook kontact -debug {-test}" KDEPIM_FEATURES="kmail* kontact* korganizer* -kalarm -kleopatra" 0 KiB

    Total: 1 package (1 reinstall), Size of downloads: 0 KiB

    >>> Verifying ebuild manifests
    >>> Running pre-merge checks for kde-apps/kdepim-15.12.2

    >>> Emerging (1 of 1) kde-apps/kdepim-15.12.2::kde
    * kdepim-15.12.2.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                         [ ok ]
    >>> Unpacking source...

(cut)

    [ 88%] Building CXX object plugins/messageviewer/bodypartformatter/ms-tnef/CMakeFiles/messageviewer_bodypartformatter_application_mstnef.dir/application_ms-tnef.cpp.o
    cd /var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2_build/plugins/messageviewer/bodypartformatter/ms-tnef && /usr/bin/x86_64-pc-linux-gnu-g++  -DKCOREADDONS_LIB -DKGUIADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DTRANSLATION_DOMAIN=\"messageviewer_application_mstnef_plugin\" -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -Dmessageviewer_bodypartformatter_application_mstnef_EXPORTS   -DQT_NO_DEBUG -DNDEBUG -mtune=generic -O2 -pipe  -std=c++0x -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2_build/plugins/messageviewer/bodypartformatter/ms-tnef -I/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2/plugins/messageviewer/bodypartformatter/ms-tnef -I/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2 -I/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2_build -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/KF5/KCalCore -isystem /usr/include/libical -isystem /usr/include/KF5 -isystem /usr/include/KF5/KDELibs4Support -isystem /usr/include/KF5/KDELibs4Support/KDE -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5/KCrash -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/KF5/KConfigWidgets -isystem /usr/include/KF5/KCodecs -isystem /usr/include/KF5/KConfigGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/KF5/KAuth -isystem /usr/include/KF5/KIOCore -isystem /usr/include/KF5/KService -isystem /usr/include/KF5/KIOFileWidgets -isystem /usr/include/KF5/KIOWidgets -isystem /usr/include/KF5/KJobWidgets -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/KF5/KCompletion -isystem /usr/include/KF5/KBookmarks -isystem /usr/include/KF5/KItemViews -isystem /usr/include/KF5/KXmlGui -isystem /usr/include/KF5/Solid -isystem /usr/include/KF5/KI18n -isystem /usr/include/KF5/KNotifications -isystem /usr/include/KF5/KIconThemes -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5/KGuiAddons -isystem /usr/include/KF5/KUnitConversion -isystem /usr/include/KF5/KTextWidgets -isystem /usr/include/KF5/SonnetUi -isystem /usr/include/KF5/KParts -isystem /usr/include/KF5/KCalUtils -isystem /usr/include/KF5/KCalUtils/kcalutils -isystem /usr/include/KF5/KMime -isystem /usr/include/KF5/MessageCore -isystem /usr/include/KF5/messagecore -isystem /usr/include/KF5/MessageViewer -isystem /usr/include/KF5/messageviewer -isystem /usr/include/KF5/KDEWebKit -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/KF5/PimCommon -isystem /usr/include/KF5/pimcommon -isystem /usr/include/KF5/KIMAP -isystem /usr/include/KF5/AkonadiCore -isystem /usr/include/KF5/akonadi/private -isystem /usr/include/KF5/KItemModels -isystem /usr/include/KF5/AkonadiWidgets -isystem /usr/include/KF5/KContacts -isystem /usr/include/KF5/Akonadi/Contact -isystem /usr/include/KF5/akonadi/contact -isystem /usr/include/KF5/Akonadi/KMime -isystem /usr/include/KF5/akonadi/kmime -isystem /usr/include/KF5/Libkleo -isystem /usr/include/KF5/libkleo -isystem /usr/include/KF5/qgpgme -isystem /usr/include/KF5/gpgme++    -fPIC -fexceptions -o CMakeFiles/messageviewer_bodypartformatter_application_mstnef.dir/application_ms-tnef.cpp.o -c /var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2/plugins/messageviewer/bodypartformatter/ms-tnef/application_ms-tnef.cpp
    /var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2/plugins/messageviewer/bodypartformatter/ms-tnef/application_ms-tnef.cpp:45:29: фатальная ошибка: ktnef/formatter.h: Нет такого файла или каталога
    #include <ktnef/formatter.h>
                                ^
    компиляция прервана.
    plugins/messageviewer/bodypartformatter/ms-tnef/CMakeFiles/messageviewer_bodypartformatter_application_mstnef.dir/build.make:62: ошибка выполнения рецепта для цели «plugins/messageviewer/bodypartformatter/ms-tnef/CMakeFiles/messageviewer_bodypartformatter_application_mstnef.dir/application_ms-tnef.cpp.o»
    make[2]: *** [plugins/messageviewer/bodypartformatter/ms-tnef/CMakeFiles/messageviewer_bodypartformatter_application_mstnef.dir/application_ms-tnef.cpp.o] Ошибка 1
    make[2]: выход из каталога «/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2_build»
    CMakeFiles/Makefile2:4722: ошибка выполнения рецепта для цели «plugins/messageviewer/bodypartformatter/ms-tnef/CMakeFiles/messageviewer_bodypartformatter_application_mstnef.dir/all»
    make[1]: *** [plugins/messageviewer/bodypartformatter/ms-tnef/CMakeFiles/messageviewer_bodypartformatter_application_mstnef.dir/all] Ошибка 2
    make[1]: выход из каталога «/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2_build»
    Makefile:127: ошибка выполнения рецепта для цели «all»
    make: *** [all] Ошибка 2
    * ERROR: kde-apps/kdepim-15.12.2::kde failed (compile phase):
    *   emake failed
    * 
    * If you need support, post the output of `emerge --info '=kde-apps/kdepim-15.12.2::kde'`,
    * the complete build log and the output of `emerge -pqv '=kde-apps/kdepim-15.12.2::kde'`.
    * The complete build log is located at '/var/log/portage/build/kde-apps/kdepim-15.12.2:20160221-063410.log'.
    * For convenience, a symlink to the build log is located at '/var/tmp/portage/kde-apps/kdepim-15.12.2/temp/build.log'.
    * The ebuild environment file is located at '/var/tmp/portage/kde-apps/kdepim-15.12.2/temp/environment'.
    * Working directory: '/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2_build'
    * S: '/var/tmp/portage/kde-apps/kdepim-15.12.2/work/kdepim-15.12.2'

**Comment by init6** [comment]
!!! existing preserved libs:
    >>> package: kde-apps/libktnef-15.12.2
     *  - /usr/lib64/libKF5Tnef.so.4.79.0
     *  - /usr/lib64/libKF5Tnef.so.5
     *      used by /usr/lib64/qt5/plugins/messageviewer_bodypartformatter_application_mstnef.so (kde-apps/kdepim-15.12.2)
    Use emerge @preserved-rebuild to rebuild packages using these libraries

**Comment by kensington** [comment]
Fixed in ae78e6a0f92cf78bf94df2348c34df5ed6435c6b by @a17r.
