### ISSUE TITLE
cannot build kde-apps/marble-9999

### ISSUE THREAD

**Issue by l29ah** [gentoo/kde#604]
```
>>> Starting src_prepare

!!! ERROR in kde-apps/marble-9999::kde:
!!! In comment_add_subdirectory at line 1828
!!! comment_add_subdirectory is banned in EAPI 6 and later - use cmake_comment_add_subdirectory instead
```

**Comment by a17r** [comment]
That's strange, I can clearly see the commit that fixed it: https://github.com/gentoo/kde/commit/a7eaeb1143299d54e9be73325fd18d461585521d

But looking at the file, it ain't there.

**Comment by l29ah** [comment]
On Wed, Feb 24, 2016 at 02:29:06AM -0800, Andreas Sturmlechner wrote:
> That's strange, I can clearly see the commit that fixed it: https://github.com/gentoo/kde/commit/a7eaeb1143299d54e9be73325fd18d461585521d
> 
> But looking at the file, it ain't there.

marble-15.12.2.ebuild ≠ marble-9999.ebuild

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by a17r** [comment]
ah, that's what lack of coffee is doing to me.

**Comment by a17r** [comment]
thx for report, solved with https://github.com/gentoo/kde/commit/b0625451429d3f3cd15d0faf8b627c8ed2cd8436
